/* =====================================================================
   BANCO DE TARJETAS — DÍGALO CON MÍMICA
   - texto:     lo que hay que actuar.
   - categoria: Escena, Personaje, Costumbre u Objeto (se muestra arriba).
   - ayuda:     idea para quien actúa (solo la ve quien actúa).
   - pista:     pista que se le puede mostrar al equipo si se traba
                (si se usa, vale menos puntos).
   ===================================================================== */

const DATOS_MIMICA = [
  { texto: 'Noaj construye el arca', categoria: 'Escena',
    ayuda: 'Martillá tablas enormes, mirá al cielo preocupado y después hacé entrar animales de a dos.',
    pista: 'Libro de Bereshit: llovió 40 días y 40 noches.' },
  { texto: 'Moshé abre el Mar Rojo', categoria: 'Escena',
    ayuda: 'Levantá un bastón con los brazos bien abiertos y separá algo pesado con las manos, como si abrieras una cortina gigante.',
    pista: 'Acababan de salir de Egipto y el agua se partió.' },
  { texto: 'Adam y Javá comen la fruta prohibida', categoria: 'Escena',
    ayuda: 'Mirá para todos lados, arrancá una fruta de un árbol, mordela y poné cara de culpa.',
    pista: 'Pasó en el Gan Edén.' },
  { texto: 'Bailar con la Torá', categoria: 'Costumbre',
    ayuda: 'Abrazá un rollo grande contra el pecho y girá bailando y saltando.',
    pista: 'Lo hacemos en las hakafot.' },
  { texto: 'Sacudir el lulav', categoria: 'Costumbre',
    ayuda: 'Sostené algo largo en una mano y algo redondo en la otra; sacudilos hacia adelante, los costados, arriba y abajo.',
    pista: 'Sucot, las cuatro especies.' },
  { texto: 'Tocar el shofar', categoria: 'Costumbre',
    ayuda: 'Llevate un cuerno imaginario a la boca, inflá los cachetes y poné cara de esfuerzo.',
    pista: 'Rosh Hashaná.' },
  { texto: 'El sueño de Iaakov con la escalera', categoria: 'Escena',
    ayuda: 'Acostate con la cabeza sobre una piedra, dormí, y después señalá algo que sube y baja.',
    pista: 'Por la escalera subían y bajaban ángeles.' },
  { texto: 'Iosef y su túnica de colores', categoria: 'Personaje',
    ayuda: 'Ponete un abrigo imaginario, desfilá orgulloso mostrándolo y señalá muchos colores distintos.',
    pista: 'Sus hermanos se pusieron celosos y lo vendieron.' },
  { texto: 'La burra de Bilaam', categoria: 'Escena',
    ayuda: 'Montá un burro que se niega a avanzar, retalo, y después hacé que el burro "te habla" con la mano como boca.',
    pista: 'Un animal que habló.' },
  { texto: 'La torre de Babel', categoria: 'Escena',
    ayuda: 'Apilá ladrillos cada vez más alto; después hacé que nadie se entiende con gestos de confusión.',
    pista: 'De ahí salieron los idiomas.' },
  { texto: 'El maná cae del cielo', categoria: 'Escena',
    ayuda: 'Mirá hacia arriba, poné las manos como cuenco, juntá algo que cae y comelo feliz.',
    pista: 'La comida del desierto.' },
  { texto: 'Moshé baja con las Tablas', categoria: 'Escena',
    ayuda: 'Bajá de una montaña con dos piedras pesadas en los brazos.',
    pista: 'Monte Sinaí, Diez Mandamientos.' },
  { texto: 'La zarza ardiente', categoria: 'Escena',
    ayuda: 'Hacé fuego con los dedos, sorprendete porque la planta no se quema y sacate los zapatos.',
    pista: 'Ahí Dios le habló a Moshé por primera vez.' },
  { texto: 'Dar vueltas alrededor de la bimá', categoria: 'Costumbre',
    ayuda: 'Caminá en círculos cantando y aplaudiendo, contá con los dedos hasta siete.',
    pista: 'Siete veces en Simjat Torá.' },
  { texto: 'Tirar caramelos a los chicos', categoria: 'Costumbre',
    ayuda: 'Hacé que tirás cosas chiquitas al aire; después hacé de chico que las atrapa y las come.',
    pista: 'Algo dulce en la sinagoga.' },
  { texto: 'Agitar una banderita', categoria: 'Costumbre',
    ayuda: 'Mové una banderita chiquita en alto mientras saltás feliz.',
    pista: 'La llevan los chicos en Simjat Torá.' },
  { texto: 'Levantar la Torá (hagbahá)', categoria: 'Costumbre',
    ayuda: 'Levantá algo pesado y ancho con los dos brazos y girá para mostrarlo a todos.',
    pista: 'Se hace para que todos vean las letras.' },
  { texto: 'Comer en la sucá', categoria: 'Costumbre',
    ayuda: 'Mirá el techo de ramas, sentate a comer y hacé que te cae una hojita en el plato.',
    pista: 'La cabaña de Sucot.' },
  { texto: 'El arcoíris', categoria: 'Objeto',
    ayuda: 'Dibujá un arco gigante en el aire, después hacé que llueve y sale el sol.',
    pista: 'La promesa después del diluvio.' },
  { texto: 'La serpiente del Gan Edén', categoria: 'Personaje',
    ayuda: 'Arrastrate o movete ondulando, sacá la lengua y ofrecé una fruta con picardía.',
    pista: 'Convenció a Javá.' },
  { texto: 'Miriam con el pandero', categoria: 'Personaje',
    ayuda: 'Bailá tocando un pandero en alto, invitando a otras a sumarse.',
    pista: 'La hermana de Moshé, después de cruzar el mar.' },
  { texto: 'Las plagas de Egipto', categoria: 'Escena',
    ayuda: 'Saltá como rana, después rascate como si tuvieras piojos, después espantá langostas.',
    pista: 'Fueron diez.' },
  { texto: 'El Faraón', categoria: 'Personaje',
    ayuda: 'Caminá como un rey soberbio, con los brazos cruzados, y negá con el dedo: "¡no, no, no!".',
    pista: 'El rey de Egipto que no dejaba salir al pueblo.' },
  { texto: 'Abraham cuenta las estrellas', categoria: 'Escena',
    ayuda: 'Mirá el cielo y contá con el dedo sin poder terminar nunca; hacé cara de asombro.',
    pista: 'Le prometieron descendientes como las estrellas.' },
  { texto: 'El sofer escribe la Torá', categoria: 'Personaje',
    ayuda: 'Mojá una pluma en tinta y escribí despacito, letra por letra, con muchísimo cuidado.',
    pista: 'El escriba.' },
  { texto: 'Leer la Torá con el iad', categoria: 'Costumbre',
    ayuda: 'Seguí las líneas con un puntero mientras cantás moviendo la cabeza.',
    pista: 'El puntero con forma de mano.' },
  { texto: 'Kol Hanearim', categoria: 'Costumbre',
    ayuda: 'Extendé un manto grande en el aire y hacé como que muchos chicos se meten abajo.',
    pista: 'Todos los chicos suben juntos a la Torá.' },
  { texto: 'Encender las velas de Shabat', categoria: 'Costumbre',
    ayuda: 'Prendé dos velas, mové las manos en círculo hacia vos y tapate los ojos.',
    pista: 'Viernes a la tarde.' },
  { texto: 'Moshé bebé en la canasta', categoria: 'Escena',
    ayuda: 'Hacé de bebé en una canasta que se mece sobre el agua; después hacé de princesa que lo encuentra.',
    pista: 'Lo encontró la hija del Faraón en el río.' },
  { texto: 'Rivká da de beber a los camellos', categoria: 'Escena',
    ayuda: 'Sacá agua de un pozo con un balde y dásela a animales altos con joroba.',
    pista: 'Así la eligieron como esposa de Itzjak.' },
  { texto: 'La creación del mundo', categoria: 'Escena',
    ayuda: 'Hacé aparecer luz, mares, plantas y animales con gestos grandes; al final, acostate a descansar.',
    pista: 'Seis días de trabajo y uno de descanso.' },
  { texto: 'Hacer kidush', categoria: 'Costumbre',
    ayuda: 'Levantá una copa, cantá con los ojos cerrados y tomá un traguito.',
    pista: 'La bendición sobre el vino.' },
  { texto: 'Trenzar la jalá', categoria: 'Costumbre',
    ayuda: 'Amasá una masa, estirala en tiras y trenzala.',
    pista: 'El pan de Shabat.' },
  { texto: 'Cruzar el desierto', categoria: 'Escena',
    ayuda: 'Caminá cansado bajo el sol, secate la frente y arrastrá los pies.',
    pista: 'Cuarenta años caminando.' },
  { texto: 'El becerro de oro', categoria: 'Escena',
    ayuda: 'Sacate aros y pulseras, tiralos al fuego y después bailá alrededor de una estatua con cuernos.',
    pista: 'Pasó mientras Moshé estaba en el monte Sinaí.' },
  { texto: 'Iaakov lucha con el ángel', categoria: 'Personaje',
    ayuda: 'Luchá con alguien invisible hasta que amanece y terminá caminando rengo.',
    pista: 'Después le cambiaron el nombre por Israel.' },
  { texto: 'La paloma con la hoja de olivo', categoria: 'Objeto',
    ayuda: 'Volá con los brazos y traé algo chiquito en la boca, muy contenta.',
    pista: 'Volvió al arca de Noaj.' },
  { texto: 'Sará se ríe', categoria: 'Escena',
    ayuda: 'Hacé de viejita que escucha una noticia increíble detrás de una carpa y se tapa la boca riéndose.',
    pista: 'Iba a tener un hijo a los 90 años.' },
  { texto: 'El Jatán Torá', categoria: 'Personaje',
    ayuda: 'Subí orgulloso, besá el rollo, y después hacé gesto de invitar a todos a comer.',
    pista: 'Recibe la última aliá de la Torá.' },
  { texto: 'Enrollar la Torá', categoria: 'Costumbre',
    ayuda: 'Girá dos rodillos para enrollar un rollo largo y después atalo con una cinta.',
    pista: 'Guelilá.' },
  { texto: 'Moshé golpea la roca', categoria: 'Escena',
    ayuda: 'Golpeá una piedra con un bastón y hacé que sale un chorro de agua que todos toman.',
    pista: 'Agua en el desierto.' }
];
