/* =====================================================================
   BANCO DE PERSONALIDADES — ¿QUIÉN ES? (fotos distorsionadas)
   - nombre:    la respuesta.
   - categoria: 'Política', 'Ciencia' o 'Arte'.
   - foto:      archivo en images/personalidades/ (cuadrada, 480x480).
   - pistas:    3 pistas, de la MÁS DIFÍCIL a la MÁS FÁCIL.
   - dato:      dato curioso que se muestra al final.
   - credito:   autor y licencia de la foto (lo pide la licencia: no borrar).
   Todas las fotos son de Wikimedia Commons, con licencia libre, recortadas.
   ===================================================================== */

const DATOS_PERSONALIDADES = [
  {"nombre": "Theodor Herzl", "categoria": "Política", "foto": "images/personalidades/theodor-herzl.jpg", "pistas": ["Fui periodista en Viena.", "Escribí el libro \"El Estado judío\" y organicé el Primer Congreso Sionista en Basilea.", "Soy el padre del sionismo político: \"Si lo quieren, no será una leyenda\"."], "dato": "Murió en 1904, 44 años antes de que naciera el Estado de Israel.", "credito": "Carl Pietzner · Public domain · Wikimedia Commons"},
  {"nombre": "David Ben-Gurión", "categoria": "Política", "foto": "images/personalidades/david-ben-gurion.jpg", "pistas": ["Nací en Płońsk, Polonia, y de viejo me fui a vivir a un kibutz en el desierto del Néguev.", "El principal aeropuerto de Israel lleva mi nombre.", "Leí la Declaración de Independencia de Israel en 1948 y fui su primer primer ministro."], "dato": "Su casa en el kibutz Sde Boker hoy es un museo.", "credito": "Fritz Cohen · Public domain · Wikimedia Commons"},
  {"nombre": "Golda Meir", "categoria": "Política", "foto": "images/personalidades/golda-meir.jpg", "pistas": ["Nací en Kiev y crecí en Milwaukee, Estados Unidos, donde fui maestra.", "Fui la primera representante de Israel en Moscú.", "Fui la primera mujer en ser primera ministra de Israel."], "dato": "Llegó a primera ministra en 1969, a los 70 años.", "credito": "Willem van de Poll · CC BY-SA 4.0 · Wikimedia Commons"},
  {"nombre": "Itzjak Rabin", "categoria": "Política", "foto": "images/personalidades/yitzhak-rabin.jpg", "pistas": ["Fui jefe del Estado Mayor del ejército en la Guerra de los Seis Días.", "Recibí el Premio Nobel de la Paz en 1994.", "Fui primer ministro de Israel y me asesinaron en 1995, al terminar un acto por la paz en Tel Aviv."], "dato": "La plaza donde lo asesinaron hoy se llama Kikar Rabin.", "credito": "Yaakov Saar · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Menajem Beguin", "categoria": "Política", "foto": "images/personalidades/menachem-begin.jpg", "pistas": ["Nací en Brest-Litovsk y dirigí el Irgún antes de la independencia.", "Mi partido, el Likud, llegó por primera vez al gobierno en 1977.", "Firmé la paz con Egipto y recibí el Nobel de la Paz junto a Anwar el-Sadat."], "dato": "Fue el primer primer ministro de Israel que no era del Partido Laborista.", "credito": "MSGT DENHAM · Public domain · Wikimedia Commons"},
  {"nombre": "Shimon Peres", "categoria": "Política", "foto": "images/personalidades/shimon-peres.jpg", "pistas": ["Estuve casi 70 años en la política israelí.", "Fui primer ministro y después presidente de Israel.", "Compartí el Premio Nobel de la Paz de 1994 con Itzjak Rabin."], "dato": "Terminó su mandato como presidente de Israel a los 90 años.", "credito": "Avi Ohayon · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Jaim Weizmann", "categoria": "Ciencia", "foto": "images/personalidades/chaim-weizmann.jpg", "pistas": ["Fui químico y mis inventos ayudaron a Gran Bretaña en la Primera Guerra Mundial.", "Un famoso instituto científico de Rejovot lleva mi nombre.", "Fui el primer presidente del Estado de Israel."], "dato": "Fue científico y líder sionista a la vez.", "credito": "Hugo Mendelson · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Moshé Dayán", "categoria": "Política", "foto": "images/personalidades/moshe-dayan.jpg", "pistas": ["Nací en Deganía, el primer kibutz.", "Fui jefe del ejército y ministro de Defensa durante la Guerra de los Seis Días.", "Me reconocen por el parche negro en el ojo."], "dato": "Perdió el ojo en 1941, en una misión en el Líbano, en la Segunda Guerra Mundial.", "credito": "IDF Spokesperson's Unit photographer · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Albert Einstein", "categoria": "Ciencia", "foto": "images/personalidades/albert-einstein.jpg", "pistas": ["Me ofrecieron ser presidente de Israel en 1952 y dije que no.", "Gané el Premio Nobel de Física en 1921.", "Soy el autor de la teoría de la relatividad: E = mc²."], "dato": "Le dejó sus escritos a la Universidad Hebrea de Jerusalem.", "credito": "Oren Jack Turner · Public domain · Wikimedia Commons"},
  {"nombre": "Sigmund Freud", "categoria": "Ciencia", "foto": "images/personalidades/sigmund-freud.jpg", "pistas": ["Viví en Viena casi toda mi vida y escapé de los nazis a Londres en 1938.", "Escribí \"La interpretación de los sueños\".", "Soy el padre del psicoanálisis."], "dato": "Su consultorio de Viena, con el famoso diván, hoy es un museo.", "credito": "Max Halberstadt · Public domain · Wikimedia Commons"},
  {"nombre": "Jonas Salk", "categoria": "Ciencia", "foto": "images/personalidades/jonas-salk.jpg", "pistas": ["Fui médico e investigador en Pittsburgh, Estados Unidos.", "No quise patentar mi descubrimiento: \"¿Se puede patentar el sol?\".", "Creé la primera vacuna efectiva contra la polio."], "dato": "Su vacuna se aprobó en 1955 y salvó a millones de chicos.", "credito": "SAS Scandinavian Airlines · Public domain · Wikimedia Commons"},
  {"nombre": "Lise Meitner", "categoria": "Ciencia", "foto": "images/personalidades/lise-meitner.jpg", "pistas": ["Fui una física austríaca y tuve que escapar de Alemania en 1938.", "Junto con mi sobrino explicamos cómo se parte el átomo: la fisión nuclear.", "El elemento químico 109, el meitnerio, lleva mi nombre."], "dato": "Su colega Otto Hahn recibió el Nobel por la fisión, pero ella no.", "credito": "Harris & Ewing · Public domain · Wikimedia Commons"},
  {"nombre": "Richard Feynman", "categoria": "Ciencia", "foto": "images/personalidades/richard-feynman.jpg", "pistas": ["Me encantaba tocar los bongós y abrir cajas fuertes por diversión.", "Unos famosos diagramas de física llevan mi nombre.", "Gané el Nobel de Física en 1965 y expliqué el accidente del transbordador Challenger con un vaso de agua helada."], "dato": "Fue uno de los grandes divulgadores de la ciencia.", "credito": "Autor desconocido · Public domain · Wikimedia Commons"},
  {"nombre": "J. Robert Oppenheimer", "categoria": "Ciencia", "foto": "images/personalidades/j-robert-oppenheimer.jpg", "pistas": ["Fui un físico que leía sánscrito.", "Dirigí el laboratorio de Los Álamos, en Nuevo México.", "Me llaman \"el padre de la bomba atómica\"; en 2023 hicieron una película con mi apellido."], "dato": "La película de Christopher Nolan ganó el Oscar a la mejor película.", "credito": "Autor desconocido · Public domain · Wikimedia Commons"},
  {"nombre": "Ada Yonath", "categoria": "Ciencia", "foto": "images/personalidades/ada-yonath.jpg", "pistas": ["Nací en Jerusalem en una familia muy humilde.", "Estudié la estructura del ribosoma, la \"fábrica\" de proteínas de las células.", "Soy la primera mujer israelí que ganó un Premio Nobel (Química, 2009)."], "dato": "Trabaja en el Instituto Weizmann de Ciencias.", "credito": "Staff photographer · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "César Milstein", "categoria": "Ciencia", "foto": "images/personalidades/cesar-milstein.jpg", "pistas": ["Nací en Bahía Blanca, Argentina.", "Trabajé muchos años en la Universidad de Cambridge, en Inglaterra.", "Gané el Nobel de Medicina en 1984 por los anticuerpos monoclonales."], "dato": "Es uno de los cinco argentinos que ganaron un Premio Nobel.", "credito": "original file: Diario La Nueva Provincia de Bahía Blanca\nderivative work: Rexmania · Public domain · Wikimedia Commons"},
  {"nombre": "Daniel Kahneman", "categoria": "Ciencia", "foto": "images/personalidades/daniel-kahneman.jpg", "pistas": ["Nací en Tel Aviv, crecí en París y estudié en la Universidad Hebrea.", "Escribí el libro \"Pensar rápido, pensar despacio\".", "Soy psicólogo y, aunque nunca estudié economía, gané el Nobel de Economía en 2002."], "dato": "Estudió cómo las personas toman decisiones y se equivocan.", "credito": "nrkbeta · CC BY-SA 2.0 · Wikimedia Commons"},
  {"nombre": "Rosalind Franklin", "categoria": "Ciencia", "foto": "images/personalidades/rosalind-franklin.jpg", "pistas": ["Fui una química inglesa y morí muy joven, a los 37 años.", "Mi famosa \"Fotografía 51\" se hizo con rayos X.", "Mi trabajo fue clave para descubrir la forma de doble hélice del ADN."], "dato": "El Nobel por el ADN se lo dieron a otros después de su muerte.", "credito": "MRC Laboratory of Molecular Biology · CC BY-SA 4.0 · Wikimedia Commons"},
  {"nombre": "Marc Chagall", "categoria": "Arte", "foto": "images/personalidades/marc-chagall.jpg", "pistas": ["Nací en Vitebsk, una ciudad de Bielorrusia que aparece en casi todos mis cuadros.", "En mis pinturas vuelan novios, vacas y violinistas.", "Hice los vitrales de las 12 tribus de Israel en el Hospital Hadasa de Jerusalem."], "dato": "También hizo los tapices de la Knéset.", "credito": "Pierre Choumoff · Public domain · Wikimedia Commons"},
  {"nombre": "Franz Kafka", "categoria": "Arte", "foto": "images/personalidades/franz-kafka.jpg", "pistas": ["Nací en Praga y trabajé en una compañía de seguros.", "Le pedí a mi amigo Max Brod que quemara mis escritos, y no me hizo caso.", "Escribí \"La metamorfosis\", donde un hombre se despierta convertido en insecto."], "dato": "Muchos de sus manuscritos están hoy en la Biblioteca Nacional de Israel.", "credito": "Fotógrafo desconocido · Public domain · Wikimedia Commons"},
  {"nombre": "Leonard Bernstein", "categoria": "Arte", "foto": "images/personalidades/leonard-bernstein.jpg", "pistas": ["Dirigí la Filarmónica de Nueva York y compuse una sinfonía llamada \"Kaddish\".", "Escribí los \"Salmos de Chichester\", cantados en hebreo.", "Compuse la música de \"West Side Story\"."], "dato": "Fue uno de los directores de orquesta más famosos del siglo XX.", "credito": "Jack Mitchell · CC BY-SA 4.0 · Wikimedia Commons"},
  {"nombre": "Groucho Marx", "categoria": "Arte", "foto": "images/personalidades/groucho-marx.jpg", "pistas": ["Hice películas con mis hermanos: Chico, Harpo y Zeppo.", "Mi bigote era pintado y siempre tenía un cigarro en la mano.", "Dije: \"No quiero pertenecer a ningún club que acepte como socio a alguien como yo\"."], "dato": "Los Hermanos Marx fueron una de las grandes familias del humor.", "credito": "ABC Photo · Public domain · Wikimedia Commons"},
  {"nombre": "Barbra Streisand", "categoria": "Arte", "foto": "images/personalidades/barbra-streisand.jpg", "pistas": ["Nací en Brooklyn y gané Oscar, Emmy, Grammy y Tony.", "Dirigí y protagonicé \"Yentl\", sobre una joven que se disfraza de varón para estudiar Talmud.", "Canté y actué en \"Funny Girl\"."], "dato": "Fue la primera mujer en escribir, producir, dirigir y protagonizar una película de un gran estudio.", "credito": "lifescript · CC BY 2.0 · Wikimedia Commons"},
  {"nombre": "Steven Spielberg", "categoria": "Arte", "foto": "images/personalidades/steven-spielberg.jpg", "pistas": ["Creé una fundación que grabó el testimonio de más de 50.000 sobrevivientes de la Shoá.", "Dirigí \"Tiburón\", \"E.T.\" y \"Jurassic Park\".", "Gané el Oscar por \"La lista de Schindler\"."], "dato": "Es uno de los directores más taquilleros de la historia.", "credito": "Martin Kraft · CC BY-SA 4.0 · Wikimedia Commons"},
  {"nombre": "Leonard Cohen", "categoria": "Arte", "foto": "images/personalidades/leonard-cohen.jpg", "pistas": ["Fui poeta y novelista canadiense antes de ser cantante.", "En 1973 fui a cantarles a los soldados israelíes durante la Guerra de Iom Kipur.", "Compuse \"Hallelujah\"."], "dato": "Su último disco salió semanas antes de su muerte, en 2016.", "credito": "Gorupdebesanez · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Bob Dylan", "categoria": "Arte", "foto": "images/personalidades/bob-dylan.jpg", "pistas": ["Mi verdadero nombre es Robert Zimmerman y hice mi bar mitzvá en Minnesota.", "Canté \"Blowin' in the Wind\" y \"Like a Rolling Stone\".", "Soy el único cantante que ganó el Premio Nobel de Literatura (2016)."], "dato": "No fue a buscar el Nobel en persona a la ceremonia.", "credito": "Raph_PH · CC BY 2.0 · Wikimedia Commons"},
  {"nombre": "Natalie Portman", "categoria": "Arte", "foto": "images/personalidades/natalie-portman.jpg", "pistas": ["Nací en Jerusalem con el nombre Neta-Lee Hershlag y estudié Psicología en Harvard.", "Fui la reina Padmé en \"Star Wars\".", "Gané el Oscar por \"El cisne negro\"."], "dato": "Habla hebreo, además de inglés, francés y otros idiomas.", "credito": "Colleen Sturtevant · CC BY 4.0 · Wikimedia Commons"},
  {"nombre": "Gal Gadot", "categoria": "Arte", "foto": "images/personalidades/gal-gadot.jpg", "pistas": ["Fui Miss Israel en 2004.", "Hice el servicio militar como instructora de entrenamiento físico.", "Soy la Mujer Maravilla en el cine."], "dato": "Nació en Petaj Tikva, Israel.", "credito": "Gage Skidmore · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Ofra Haza", "categoria": "Arte", "foto": "images/personalidades/ofra-haza.jpg", "pistas": ["Mi familia vino de Yemen y crecí en el barrio Hatikva de Tel Aviv.", "Salí segunda en Eurovisión 1983 con la canción \"Jai\".", "Mi versión de \"Im nin'alu\" fue un éxito en todo el mundo."], "dato": "Puso la voz de la mamá de Moshé en la película animada \"El príncipe de Egipto\".", "credito": "Yaakov Saar · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Naomi Shemer", "categoria": "Arte", "foto": "images/personalidades/naomi-shemer.jpg", "pistas": ["Nací en Kvutzat Kinéret, a orillas del lago Kinéret.", "Escribí \"Al kol ele\" y \"Lu iehí\".", "Compuse \"Ierushalaim shel zahav\" (Jerusalem de oro)."], "dato": "Muchos la llaman \"la primera dama de la canción israelí\".", "credito": "Yaakov Saar · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Amos Oz", "categoria": "Arte", "foto": "images/personalidades/amos-oz.jpg", "pistas": ["Nací en Jerusalem y viví muchos años en el kibutz Hulda.", "Mi apellido quiere decir \"fuerza\" en hebreo, y lo elegí yo.", "Escribí \"Una historia de amor y oscuridad\"."], "dato": "Fue uno de los escritores israelíes más traducidos del mundo.", "credito": "Gotfryd, Bernard, photographer · Public domain · Wikimedia Commons"},
  {"nombre": "Itzhak Perlman", "categoria": "Arte", "foto": "images/personalidades/itzhak-perlman.jpg", "pistas": ["Nací en Tel Aviv y tuve polio de chico, por eso toco sentado.", "Toqué el violín en la música de \"La lista de Schindler\".", "Soy uno de los violinistas más famosos del mundo."], "dato": "Ganó 16 premios Grammy.", "credito": "Kenneth C. Zirkel · CC BY-SA 4.0 · Wikimedia Commons"},
  {"nombre": "Daniel Barenboim", "categoria": "Arte", "foto": "images/personalidades/daniel-barenboim.jpg", "pistas": ["Nací en Buenos Aires en 1942 y di mi primer concierto de piano a los 7 años.", "Fundé una orquesta de jóvenes israelíes y árabes que tocan juntos.", "Soy pianista y director de orquesta; dirigí la Ópera Estatal de Berlín y la Scala de Milán."], "dato": "Su orquesta se llama West-Eastern Divan.", "credito": "Raimond Spekking · CC BY-SA 4.0 · Wikimedia Commons"},
  {"nombre": "Arik Einstein", "categoria": "Arte", "foto": "images/personalidades/arik-einstein.jpg", "pistas": ["De joven fui campeón de atletismo.", "Canté \"Ani vejá\" (\"Vos y yo vamos a cambiar el mundo\").", "Soy una de las voces más queridas de la canción israelí y comparto apellido con un famoso físico."], "dato": "Cuando murió, en 2013, miles de personas cantaron sus canciones en las calles.", "credito": "Yaakov Saar · CC BY-SA 3.0 · Wikimedia Commons"},
  {"nombre": "Alejandra Pizarnik", "categoria": "Arte", "foto": "images/personalidades/alejandra-pizarnik.jpg", "pistas": ["Nací en Avellaneda, hija de inmigrantes judíos de Europa del Este.", "Viví en París y trabajé en revistas literarias.", "Soy poeta argentina y escribí \"Árbol de Diana\"."], "dato": "Es una de las grandes poetas de la literatura argentina.", "credito": "Sara Facio · Public domain · Wikimedia Commons"}
];
