/* =====================================================================
   BANCO DE ADIVINANZAS — ¿QUIÉN SOY? / ¿QUÉ SOY?
   - respuesta: lo que hay que adivinar.
   - tipo:      'personaje' (¿Quién soy?) u 'objeto' (¿Qué soy?).
   - pistas:    3 pistas, de la MÁS DIFÍCIL a la MÁS FÁCIL.
                Con la 1ª vale 3 puntos, con la 2ª 2, con la 3ª 1.
   - dato:      (opcional) dato curioso que se muestra al final.
   ===================================================================== */

const DATOS_QUIEN_SOY = [
  { respuesta: 'Noaj', tipo: 'personaje',
    pistas: ['Mis hijos se llamaban Shem, Jam e Iéfet.', 'Hice un viaje larguísimo con muchísima compañía animal.', 'Construí un arca para salvarme del diluvio.'],
    dato: 'Su nombre es también el de la segunda parashá de la Torá.' },
  { respuesta: 'Moshé', tipo: 'personaje',
    pistas: ['Me crió la hija de un rey.', 'Hablé con Dios frente a un arbusto que ardía sin quemarse.', 'Saqué al pueblo de Egipto y recibí la Torá en el Sinaí.'],
    dato: 'Su muerte se lee en Vezot Haberajá, en Simjat Torá.' },
  { respuesta: 'Abraham', tipo: 'personaje',
    pistas: ['Salí de mi tierra sin saber adónde iba, porque Dios me lo pidió.', 'Recibí a tres visitantes misteriosos en mi carpa.', 'Soy el primer patriarca, esposo de Sará.'] },
  { respuesta: 'Sará', tipo: 'personaje',
    pistas: ['Me reí cuando escuché una noticia a los 90 años.', 'El nombre de mi hijo significa "reirá".', 'Soy la primera matriarca, esposa de Abraham.'] },
  { respuesta: 'Iaakov', tipo: 'personaje',
    pistas: ['Trabajé catorce años por la mujer que amaba.', 'Luché con un ángel y me cambiaron el nombre.', 'Soñé con una escalera; mis doce hijos son las tribus.'] },
  { respuesta: 'Iosef', tipo: 'personaje',
    pistas: ['Interpreté los sueños de un rey.', 'Llegué a ser virrey de Egipto.', 'Mis hermanos me vendieron por celos de mi túnica especial.'] },
  { respuesta: 'Aharón', tipo: 'personaje',
    pistas: ['Mi vara floreció y dio almendras.', 'Hablaba ante el Faraón en lugar de mi hermano.', 'Fui el primer Kohen Gadol.'] },
  { respuesta: 'Miriam', tipo: 'personaje',
    pistas: ['Cuidé a mi hermanito, escondida entre los juncos del río.', 'Según el midrash, donde yo estaba había un pozo de agua.', 'Canté con un pandero después de cruzar el mar.'] },
  { respuesta: 'Iehoshúa', tipo: 'personaje',
    pistas: ['Fui uno de los doce espías y traje buenas noticias.', 'Con mi libro empieza la haftará de Simjat Torá.', 'Fui el sucesor de Moshé.'] },
  { respuesta: 'Adam', tipo: 'personaje',
    pistas: ['Les puse nombre a todos los animales.', 'No tuve ni papá ni mamá.', 'Fui el primer ser humano.'] },
  { respuesta: 'Javá', tipo: 'personaje',
    pistas: ['Me llaman "la madre de todos los vivientes".', 'Vivía en un jardín hermoso.', 'Comí del árbol prohibido.'] },
  { respuesta: 'Kain', tipo: 'personaje',
    pistas: ['Era agricultor.', 'Pregunté: "¿Acaso soy yo el guardián de mi hermano?".', 'Maté a mi hermano Hével.'] },
  { respuesta: 'Rivká', tipo: 'personaje',
    pistas: ['Les di de beber a los camellos de un forastero.', 'Tuve mellizos que se peleaban desde la panza.', 'Fui la esposa de Itzjak.'] },
  { respuesta: 'Rajel', tipo: 'personaje',
    pistas: ['Me llevé escondidos los ídolos de mi papá.', 'Por mí trabajaron siete años que parecieron pocos días.', 'Fui la mamá de Iosef y Biniamín.'] },
  { respuesta: 'Itzjak', tipo: 'personaje',
    pistas: ['Cavé pozos que otros me tapaban.', 'De viejo me quedé casi ciego y bendije a mis hijos.', 'Mi nombre significa "reirá" y mi papá fue Abraham.'] },
  { respuesta: 'Bilaam', tipo: 'personaje',
    pistas: ['Un rey me contrató para maldecir a Israel.', 'Terminé bendiciendo: "¡Qué lindas son tus carpas, Iaakov!".', 'Mi burra me habló.'],
    dato: 'Su frase "Ma tovu" se reza al entrar a la sinagoga.' },
  { respuesta: 'El Faraón', tipo: 'personaje',
    pistas: ['Mi corazón se endureció una y otra vez.', 'Sufrí diez plagas.', 'Soy el rey de Egipto que no quería dejar salir al pueblo.'] },
  { respuesta: 'Betzalel', tipo: 'personaje',
    pistas: ['Mi nombre significa "a la sombra de Dios".', 'Sabía trabajar el oro, la plata, la madera y las piedras.', 'Construí el Mishkán en el desierto.'] },
  { respuesta: 'Kóraj', tipo: 'personaje',
    pistas: ['Hay una parashá con mi nombre.', 'Me rebelé contra Moshé y Aharón.', 'Me tragó la tierra.'] },
  { respuesta: 'La mujer de Lot', tipo: 'personaje',
    pistas: ['Vivía en Sodoma.', 'Me dijeron que no mirara para atrás.', 'Me convertí en una estatua de sal.'] },

  { respuesta: 'El Sefer Torá', tipo: 'objeto',
    pistas: ['Tengo unas 304.805 letras.', 'Me visten con un manto y a veces con una corona.', 'Soy un rollo de pergamino escrito a mano.'] },
  { respuesta: 'El shofar', tipo: 'objeto',
    pistas: ['Casi siempre soy de cuerno de carnero.', 'Conmigo suenan tekiá, shevarim y truá.', 'Me tocan en Rosh Hashaná.'] },
  { respuesta: 'El etrog', tipo: 'objeto',
    pistas: ['Tengo una puntita (pitam) que conviene que no se rompa.', 'Me guardan en una cajita especial, envuelto.', 'Soy la fruta amarilla de las cuatro especies.'] },
  { respuesta: 'La sucá', tipo: 'objeto',
    pistas: ['Mi techo se llama sjaj.', 'A través de mi techo se tienen que ver las estrellas.', 'Soy la cabaña de Sucot.'] },
  { respuesta: 'El iad', tipo: 'objeto',
    pistas: ['Evito que los dedos toquen el pergamino.', 'Suelo ser de plata o de madera.', 'Soy un puntero con forma de manito.'] },
  { respuesta: 'El arcoíris', tipo: 'objeto',
    pistas: ['Soy una promesa.', 'Aparezco cuando sale el sol después de la lluvia.', 'Soy la señal que puso Dios después del diluvio.'] },
  { respuesta: 'La banderita de Simjat Torá', tipo: 'objeto',
    pistas: ['Antes me ponían una manzana en la punta.', 'Me llevan los chicos.', 'Me agitan en las hakafot.'] },
  { respuesta: 'El maná', tipo: 'objeto',
    pistas: ['Tenía gusto a masa con miel.', 'Los viernes caía el doble.', 'Caía del cielo en el desierto.'] },
  { respuesta: 'Las Tablas de la Ley', tipo: 'objeto',
    pistas: ['La primera vez nos rompieron.', 'Estábamos escritas de los dos lados.', 'Tenemos los Diez Mandamientos.'] },
  { respuesta: 'La Menorá del Mishkán', tipo: 'objeto',
    pistas: ['Me hicieron de una sola pieza de oro.', 'Iluminaba el Mishkán.', 'Tengo siete brazos.'] },
  { respuesta: 'El Arón Hakódesh', tipo: 'objeto',
    pistas: ['Tengo una cortina que se llama parójet.', 'Suelo estar en la pared que mira hacia Jerusalem.', 'Guardo los Sifrei Torá.'] },
  { respuesta: 'El talit', tipo: 'objeto',
    pistas: ['Tengo flecos llamados tzitzit en mis cuatro esquinas.', 'En Kol Hanearim me extienden sobre los chicos.', 'Soy el manto de oración.'] }
];
