/* =====================================================================
   BANCO DE HISTORIAS — ¿VERDAD O MENTIRA DEL RABINO?

   - historia:    lo que cuenta el Rabino (se lee en voz alta).
   - verdad:      true si es verdad, false si es invento.
   - explicacion: se muestra al revelar. En las mentiras, aclarar SIEMPRE
                  que es inventado (y, si sirve, cuál es el dato real).
   - fuente:      de dónde sale (para las verdaderas).
   - revisar:     true = conviene chequearla.
   ===================================================================== */

const DATOS_RABINO = [

  /* ================== VERDADERAS ================== */

  { verdad: true, fuente: 'Talmud, Shabat 31a',
    historia: 'Un hombre le pidió a Hilel que le enseñara toda la Torá mientras él se paraba en un solo pie. Hilel no se enojó y se la resumió en una frase.',
    explicacion: 'Hilel le dijo: "Lo que no te gusta a vos, no se lo hagas a tu prójimo. Eso es toda la Torá; el resto es explicación. Andá y estudiá".' },
  { verdad: true, fuente: 'Talmud, Taanit 23a',
    historia: 'Un sabio llamado Joni dibujó un círculo en el piso, se metió adentro y juró que no iba a salir hasta que lloviera. Y llovió.',
    explicacion: 'Por eso lo llamaron Joni Hameaguel, "Joni el que hace círculos".' },
  { verdad: true, fuente: 'Talmud, Taanit 23a',
    historia: 'Ese mismo Joni se quedó dormido debajo de un árbol… y se despertó 70 años después.',
    explicacion: 'Vio a un hombre plantar un algarrobo, que tarda 70 años en dar frutos, se durmió, y al despertar el nieto de aquel hombre comía sus algarrobas.' },
  { verdad: true, fuente: 'Avot de Rabí Natán 6',
    historia: 'Rabí Akiva no sabía leer hasta los 40 años. Se animó a estudiar cuando vio que unas gotas de agua habían agujereado una piedra.',
    explicacion: 'Pensó: "Si el agua, que es blanda, puede agujerear la piedra, la Torá, que es fuerte, puede entrar en mi corazón".' },
  { verdad: true, fuente: 'Talmud, Nedarim 50a',
    historia: 'La esposa de Rabí Akiva vendió sus trenzas para que su marido pudiera seguir estudiando.',
    explicacion: 'Rajel, su esposa, lo apoyó durante los muchos años de estudio.' },
  { verdad: true, fuente: 'Talmud, Sotá 37a',
    historia: 'Frente al Mar Rojo, un hombre llamado Najshón se metió al agua hasta la nariz antes de que el mar se abriera.',
    explicacion: 'Según el Talmud, el mar se abrió cuando Najshón ben Aminadav se animó a entrar primero.' },
  { verdad: true, fuente: 'Talmud, Bava Metzia 59b',
    historia: 'En una discusión, un sabio hizo que un árbol se moviera y un arroyo corriera al revés para demostrar que tenía razón. Los demás sabios igual votaron en contra.',
    explicacion: 'Hasta una voz del cielo le dio la razón a Rabí Eliezer, pero los sabios dijeron: "La Torá no está en el cielo". Y el Talmud cuenta que Dios sonrió: "Mis hijos me vencieron".' },
  { verdad: true, fuente: 'Talmud, Guitín 56a',
    historia: 'Durante el sitio de Jerusalem, un gran sabio salió de la ciudad escondido dentro de un ataúd.',
    explicacion: 'Rabán Iojanán ben Zakai se hizo pasar por muerto, salió, y le pidió al general romano la ciudad de Iavne para seguir estudiando Torá.' },
  { verdad: true, fuente: 'Talmud, Berajot 59a',
    historia: 'Existe una bendición especial para decir cuando uno ve un arcoíris.',
    explicacion: 'Recuerda la promesa que Dios le hizo a Noaj después del diluvio.' },
  { verdad: true, fuente: 'Talmud, Berajot 58b',
    historia: 'Existe una bendición para decir cuando uno ve a una persona muy alta o muy bajita.',
    explicacion: 'Se dice "meshané habriot": bendito el que hace a las criaturas distintas.' },
  { verdad: true, fuente: 'Mishná, Berajot 9:2',
    historia: 'Existe una bendición especial para decir cuando uno escucha un trueno.',
    explicacion: '"Shekojó ugburató malé olam": cuyo poder llena el mundo.' },
  { verdad: true, fuente: 'Talmud, Berajot 58a',
    historia: 'Existe una bendición para decir cuando uno ve a un gran sabio, aunque no sea judío.',
    explicacion: 'Se bendice a quien "dio de su sabiduría a los seres humanos".' },
  { verdad: true, fuente: 'Midrash Shemot Rabá 1:26',
    historia: 'Según un midrash, Moshé de bebé se metió una brasa encendida en la boca, y por eso hablaba con dificultad.',
    explicacion: 'El Faraón lo puso a prueba con oro y brasas; un ángel le desvió la mano hacia la brasa.' },
  { verdad: true, fuente: 'Midrash Bereshit Rabá 38:13',
    historia: 'Según el midrash, Abraham rompió los ídolos de su papá y le echó la culpa al ídolo más grande.',
    explicacion: 'Le dejó el palo en la mano al ídolo grande. Cuando su papá dijo que un ídolo no puede hacer eso, Abraham le contestó: "¿Y entonces por qué los adorás?".' },
  { verdad: true, fuente: 'Sifrí, Devarim 343',
    historia: 'Según el midrash, antes de dársela a Israel, Dios les ofreció la Torá a otros pueblos, y no la quisieron.',
    explicacion: 'Cada pueblo preguntó qué decía, y encontró algún mandamiento que no quería cumplir.' },
  { verdad: true, fuente: 'Midrash Shemot Rabá 29:9',
    historia: 'Según el midrash, cuando se entregó la Torá en el Sinaí, ningún pájaro cantó y ningún buey mugió.',
    explicacion: 'El mundo entero hizo silencio para escuchar.' },
  { verdad: true, fuente: 'Historia (1947)',
    historia: 'Los Rollos del Mar Muerto, los manuscritos bíblicos más antiguos, los encontró un pastor que buscaba una cabra perdida.',
    explicacion: 'En 1947 un pastor beduino tiró una piedra en una cueva de Qumrán y escuchó que se rompía una vasija.' },
  { verdad: true, fuente: 'Historia',
    historia: 'El hijo de Eliezer Ben-Iehudá fue criado para ser el primer chico en siglos que tuviera el hebreo como idioma materno.',
    explicacion: 'Itamar Ben-Avi creció escuchando solo hebreo en su casa, mientras su papá inventaba palabras nuevas.' },
  { verdad: true, fuente: 'Historia',
    historia: 'Al Kéter de Aram Tzová, uno de los manuscritos de la Biblia más importantes del mundo, le falta cerca del 40% de sus páginas.',
    explicacion: 'Se perdieron después de los disturbios de Alepo (Siria) en 1947. Hoy está en el Museo de Israel.' },
  { verdad: true, fuente: 'Talmud, Taanit 25a',
    historia: 'Un viernes, la hija de un sabio se equivocó y puso vinagre en lugar de aceite en las velas de Shabat. Las velas igual ardieron toda la noche.',
    explicacion: 'Rabí Janiná ben Dosa le dijo: "El que le ordenó al aceite que arda, le ordenará al vinagre que arda".' },
  { verdad: true, fuente: 'Talmud, Sucá 53a',
    historia: 'En los festejos de Sucot del Templo, un gran sabio hacía malabares con ocho antorchas encendidas.',
    explicacion: 'Era Rabán Shimón ben Gamliel, en la Simjat Beit Hashoevá. ¡La fiesta iluminaba toda Jerusalem!' },
  { verdad: true, fuente: 'Talmud, Iomá 35b',
    historia: 'Hilel, de joven, no podía pagar la entrada a la casa de estudio, así que se subió al techo a escuchar por la ventana… y quedó tapado de nieve.',
    explicacion: 'Era Shabat a la mañana; lo encontraron congelado y lo salvaron.' },
  { verdad: true, fuente: 'Talmud, Eruvin 53b',
    historia: 'Un sabio famoso contó que en su vida solo le ganaron una discusión tres personas: una mujer, una nena y un nene.',
    explicacion: 'Rabí Iehoshúa ben Jananiá reconocía con humor que lo habían vencido con su ingenio.' },
  { verdad: true, fuente: 'Historia',
    historia: 'La melodía del Hatikva se parece mucho a una obra de música clásica sobre un río de Europa.',
    explicacion: 'Se parece a "El Moldava" de Smetana: las dos vienen de una antigua canción popular.' },
  { verdad: true, fuente: 'Historia',
    historia: 'Maimónides, además de gran rabino, fue médico en la corte del sultán Saladino, en Egipto.',
    explicacion: 'Atendía a la corte de día y a su comunidad de noche.' },
  { verdad: true, fuente: 'Historia',
    historia: 'Rashi, el gran comentarista de la Torá, no tuvo hijos varones: tuvo tres hijas.',
    explicacion: 'Y sus nietos, hijos de sus hijas, fueron grandes sabios.' },
  { verdad: true, fuente: 'Historia',
    historia: 'En sus comentarios, Rashi usó cientos de palabras en francés antiguo para explicar palabras difíciles.',
    explicacion: 'Vivía en Troyes, Francia. ¡Hoy esos comentarios sirven para estudiar cómo se hablaba francés hace 900 años!' },
  { verdad: true, fuente: 'Tradición',
    historia: 'Cada tratado del Talmud empieza en la página 2: no existe la página 1.',
    explicacion: 'La primera hoja es la portada. Se dice que es para recordar que nunca terminamos de aprender, y que nunca empezamos desde cero.' },
  { verdad: true, fuente: 'Devarim 22:6-7',
    historia: 'La Torá manda espantar a la mamá pájaro antes de tomar los huevos de un nido, y promete larga vida a quien lo cumple.',
    explicacion: 'Es la mitzvá de "shiluaj hakén".' },
  { verdad: true, fuente: 'Devarim 25:4',
    historia: 'La Torá prohíbe ponerle un bozal a un buey mientras trilla el trigo, para que pueda comer mientras trabaja.',
    explicacion: 'Es uno de los mandamientos sobre cómo tratar bien a los animales.' },
  { verdad: true, fuente: 'Arqueología (Cueva de las Cartas)',
    historia: 'Se encontró una carta de Bar Kojba, el líder de la rebelión contra Roma, pidiendo que le mandaran lulav y etrog para Sucot.',
    explicacion: 'En plena guerra, pedía las cuatro especies para sus soldados.' },
  { verdad: true, fuente: 'Historia (1909)',
    historia: 'Los terrenos de las primeras casas de Tel Aviv se sortearon con caracoles de la playa.',
    explicacion: 'En 1909, 66 familias sacaron caracoles blancos y grises con sus nombres y números de terreno.' },
  { verdad: true, fuente: 'Costumbre actual',
    historia: 'Los papelitos que la gente deja en el Kotel se juntan dos veces por año y se entierran en el Monte de los Olivos.',
    explicacion: 'Como tienen el nombre de Dios o pedidos personales, no se tiran: se entierran.' },
  { verdad: true, fuente: 'Historia (1903)',
    historia: 'Gran Bretaña le ofreció a Herzl un territorio en África para crear un hogar judío.',
    explicacion: 'Fue el "Plan Uganda" (en realidad era en Kenia). El Congreso Sionista lo terminó rechazando.' },
  { verdad: true, fuente: 'Talmud, Menajot 43b',
    historia: 'Según el Talmud, una persona debería decir 100 bendiciones por día.',
    explicacion: 'Con los rezos y las bendiciones de la comida, se llega a cien.' },
  { verdad: true, fuente: 'Talmud, Berajot 54b',
    historia: 'Según el Talmud, Moshé medía diez amot de alto: ¡unos cinco metros!',
    explicacion: 'Y con un hacha también de diez amot, saltó diez amot para vencer al gigante Og.' },
  { verdad: true, fuente: 'Devarim 3:11',
    historia: 'La Torá dice que el gigante Og tenía una cama de hierro de nueve amot de largo: más de cuatro metros.',
    explicacion: 'Og era el rey de Bashán, el último de los gigantes.' },
  { verdad: true, fuente: 'Talmud, Nidá 61a',
    historia: 'Según el Talmud, el gigante Og sobrevivió al diluvio agarrado del arca de Noaj.',
    explicacion: 'Lo llaman "hapalit", el que escapó.' },
  { verdad: true, fuente: 'Talmud, Iomá 75a',
    historia: 'Según los sabios, el maná tenía el gusto de lo que cada persona quisiera.',
    explicacion: 'Cada uno sentía el sabor que tenía ganas de comer.' },
  { verdad: true, fuente: 'Talmud, Shabat 33b',
    historia: 'Un sabio y su hijo vivieron escondidos doce años en una cueva, comiendo algarrobas y tomando agua de un manantial.',
    explicacion: 'Rabí Shimón bar Iojai se escondía de los romanos. Por él se festeja Lag Baómer.' },
  { verdad: true, fuente: 'Talmud, Meguilá 18b',
    historia: 'Un sabio escribió de memoria toda la Meguilat Ester, sin mirar ningún libro.',
    explicacion: 'Rabí Meir, que además era escriba.' },
  { verdad: true, fuente: 'Historia (1896)',
    historia: 'Un depósito de papeles viejos de una sinagoga de El Cairo guardaba más de 300.000 fragmentos de manuscritos antiguos.',
    explicacion: 'Es la Guenizá de El Cairo. Dos hermanas mellizas escocesas avisaron del hallazgo a Solomon Schechter.' },
  { verdad: true, fuente: 'Bereshit 46:23',
    historia: 'Uno de los versículos más cortos de la Torá dice solamente: "Y los hijos de Dan: Jushim".',
    explicacion: 'En hebreo son apenas tres palabras.' },
  { verdad: true, fuente: 'Talmud, Berajot 62a',
    historia: 'Según el Talmud, un alumno se escondió debajo de la cama de su maestro para aprender de él. Cuando lo descubrieron, dijo: "¡Es Torá y necesito aprenderla!".',
    explicacion: 'Rav Kahana, alumno de Rav. El Talmud cuenta la historia con humor.' },
  { verdad: true, fuente: 'Historia (1967)',
    historia: 'Naomi Shemer agregó una estrofa nueva a "Ierushalaim shel zahav" pocas semanas después de escribirla.',
    explicacion: 'La compuso antes de la Guerra de los Seis Días, y después de la guerra sumó la estrofa del regreso a la Ciudad Vieja.' },
  { verdad: true, fuente: 'Historia',
    historia: 'La Knéset tiene 120 miembros por la Gran Asamblea de sabios de la época del Segundo Templo.',
    explicacion: 'La "Knéset Haguedolá" también tenía 120 miembros.' },
  { verdad: true, fuente: 'Historia',
    historia: 'La menorá del escudo de Israel está copiada de la que aparece en un arco de triunfo romano.',
    explicacion: 'Es el Arco de Tito, en Roma, que muestra a los romanos llevándose la menorá del Templo.' },
  { verdad: true, fuente: 'Historia',
    historia: 'David Ben-Gurión se paraba de cabeza en la playa para hacer ejercicio, y hasta lo fotografiaron.',
    explicacion: 'Practicaba el método Feldenkrais; la foto de 1957 en Herzlía es famosa.' },
  { verdad: true, fuente: 'Historia',
    historia: 'Albert Einstein tocaba el violín y le había puesto nombre: Lina.',
    explicacion: 'Decía que si no hubiera sido físico, habría sido músico.' },
  { verdad: true, fuente: 'Iehoshúa 6',
    historia: 'Las murallas de Jericó se cayeron después de que el pueblo diera siete vueltas alrededor de la ciudad tocando shofarot.',
    explicacion: '¡Siete vueltas, como las hakafot!' },
  { verdad: true, fuente: 'Historia',
    historia: 'En Jerusalem hay una ley que obliga a que los edificios estén recubiertos de piedra.',
    explicacion: 'Viene de 1918, de la época británica: por eso la ciudad tiene ese color dorado.' },
  { verdad: true, fuente: 'Talmud, Shabat 12b',
    historia: 'Según el Talmud, los ángeles no entienden el arameo.',
    explicacion: 'El Talmud lo menciona al hablar de en qué idioma conviene rezar por un enfermo.' },
  { verdad: true, fuente: 'Talmud, Bava Kamá 82a',
    historia: 'Ezra el escriba estableció la costumbre de comer ajo los viernes.',
    explicacion: 'Era una de sus diez disposiciones: el Talmud dice que el ajo alimenta y alegra.' },
  { verdad: true, fuente: 'Shemot 28:33-35',
    historia: 'El manto del Kohen Gadol tenía campanitas de oro colgando del borde.',
    explicacion: 'Se escuchaban cuando entraba y salía del Santuario.' },
  { verdad: true, fuente: 'Costumbre',
    historia: 'En muchas comunidades, el primer día en el jéder los chicos lamían miel puesta sobre las letras del alef-bet.',
    explicacion: 'Para que el estudio de la Torá les quedara asociado a algo dulce.' },
  { verdad: true, fuente: 'Talmud, Sotá 12b',
    historia: 'Según el Talmud, cuando la hija del Faraón vio la canasta de Moshé en el río, el brazo se le estiró para poder alcanzarla.',
    explicacion: 'Se llamaba Batia, "hija de Dios".' },
  { verdad: true, fuente: 'Talmud, Taanit 9a',
    historia: 'Según la tradición, un pozo de agua acompañó al pueblo por el desierto gracias a Miriam.',
    explicacion: 'Es el "pozo de Miriam": cuando ella murió, el agua dejó de salir.' },
  { verdad: true, fuente: 'Pirkei Avot 5:6',
    historia: 'Según la Mishná, la boca de la burra de Bilaam fue creada en el atardecer del sexto día de la Creación.',
    explicacion: 'Junto con el arcoíris, el maná y otras cosas "especiales".' },
  { verdad: true, fuente: 'Talmud, Sotá 48b',
    historia: 'Según el Talmud, para construir el Templo sin herramientas de hierro se usó un gusanito que cortaba las piedras.',
    explicacion: 'Se llamaba "shamir".' },
  { verdad: true, fuente: 'Historia',
    historia: 'Leonard Cohen vivió cinco años como monje budista en un monasterio de California.',
    explicacion: 'Y aun así siguió diciendo que era judío y cantando canciones con temas bíblicos.' },
  { verdad: true, fuente: 'Historia (1983)',
    historia: 'Bob Dylan festejó el bar mitzvá de su hijo en el Kotel.',
    explicacion: 'Fue en 1983, en Jerusalem.' },
  { verdad: true, fuente: 'Historia',
    historia: 'En Curaçao, en el Caribe, hay una sinagoga de casi 300 años con el piso cubierto de arena.',
    explicacion: 'La sinagoga Mikvé Israel-Emanuel. Se dice que recuerda los 40 años en el desierto.' },
  { verdad: true, fuente: 'Leyenda de Praga',
    historia: 'Según una leyenda de Praga, un rabino creó un gigante de barro, el Golem, y lo guardó en el altillo de la sinagoga.',
    explicacion: 'La leyenda se cuenta del Maharal de Praga y la sinagoga Altneu. (Que exista la leyenda es verdad; el Golem… ¡quién sabe!)' },
  { verdad: true, fuente: 'Talmud, Ievamot 62b',
    historia: 'Según el Talmud, Rabí Akiva llegó a tener 24.000 alumnos.',
    explicacion: 'Eran "12.000 parejas de alumnos". Según la tradición murieron en los días del Ómer, y por eso es una época de duelo.' },
  { verdad: true, fuente: 'Maimónides, Hiljot Deot 4:5',
    historia: 'Maimónides daba consejos de salud, como dormir primero del lado izquierdo y después del lado derecho.',
    explicacion: 'Sus libros incluyen muchos consejos médicos para la vida diaria.' },
  { verdad: true, fuente: 'Historia',
    historia: 'Antes de ser líder sionista, Theodor Herzl escribía obras de teatro.',
    explicacion: 'Era periodista y dramaturgo en Viena.' },
  { verdad: true, fuente: 'Historia',
    historia: 'En China hubo durante siglos una comunidad judía, con su propia sinagoga y sus Sifrei Torá.',
    explicacion: 'Los judíos de Kaifeng, que llegaron hace unos mil años.' },

  /* ================== MENTIRAS (inventadas) ================== */

  { verdad: false,
    historia: 'El Talmud dice que quien baila las siete hakafot sin parar queda exento de ayunar en Iom Kipur.',
    explicacion: '¡Mentira! No existe tal cosa. Bailar en las hakafot es una alegría, no un "canje" por el ayuno.' },
  { verdad: false,
    historia: 'En la Toledo medieval, las hakafot de Simjat Torá se hacían a caballo alrededor de la sinagoga.',
    explicacion: '¡Mentira! Es un invento. Las hakafot se hacen caminando y bailando.' },
  { verdad: false,
    historia: 'Según el midrash, Moshé tenía un gato llamado Tzipor que lo acompañó los 40 años del desierto.',
    explicacion: '¡Mentira! Tzipora era el nombre de su esposa, no de un gato.' },
  { verdad: false,
    historia: 'El Talmud prohíbe comer el etrog en Shabat para que "la fruta no se ofenda".',
    explicacion: '¡Mentira! No existe esa regla. Muchos hacen mermelada de etrog después de Sucot.' },
  { verdad: false,
    historia: 'En el Templo de Jerusalem había un coro de loros entrenados para repetir los Salmos.',
    explicacion: '¡Mentira! Los que cantaban en el Templo eran los leviím.' },
  { verdad: false,
    historia: 'Rabí Akiva aprendió el alef-bet gracias a un burro que sabía las letras.',
    explicacion: '¡Mentira! Lo que lo inspiró fueron unas gotas de agua que habían agujereado una piedra.' },
  { verdad: false,
    historia: 'El primer Sefer Torá hecho en una imprenta se imprimió en Venecia y todavía se usa en Simjat Torá.',
    explicacion: '¡Mentira! Un Sefer Torá siempre se escribe a mano. Los libros impresos, como el Jumash, no sirven para la lectura pública.' },
  { verdad: false,
    historia: 'Según la tradición, el arca de Noaj tenía una sucá en el techo para festejar Sucot durante el diluvio.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'Existe una bendición especial para decir antes de tomar un helado de chocolate.',
    explicacion: '¡Mentira! El helado lleva la bendición común "shehakol", como casi todo lo que no es pan, fruta o verdura.' },
  { verdad: false,
    historia: 'Por ley, en Israel, el presidente del país tiene que leer la última aliá de la Torá en Simjat Torá.',
    explicacion: '¡Mentira! No existe esa ley.' },
  { verdad: false,
    historia: 'Golda Meir tenía un loro que hablaba en ídish y lo llevaba a las reuniones de gobierno.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'La jalá trenzada se inventó en Tel Aviv en 1950, en un concurso de panaderos.',
    explicacion: '¡Mentira! La jalá trenzada tiene varios siglos, de las comunidades de Europa.' },
  { verdad: false,
    historia: 'El Talmud tiene un tratado entero dedicado a cómo contar chistes.',
    explicacion: '¡Mentira! El Talmud tiene mucho humor, pero no hay un tratado de chistes.' },
  { verdad: false,
    historia: 'El rey David tocaba el shofar tan fuerte que una vez derrumbó una muralla de Jerusalem.',
    explicacion: '¡Mentira! Las murallas que cayeron con shofarot fueron las de Jericó, en tiempos de Iehoshúa.' },
  { verdad: false,
    historia: 'Los rimonim del Sefer Torá se llaman así porque al principio se hacían con granadas de verdad, ahuecadas.',
    explicacion: '¡Mentira! Se llaman así por su forma de granada, pero siempre fueron de metal.' },
  { verdad: false,
    historia: 'El Sanedrín tenía 613 jueces, uno por cada mitzvá.',
    explicacion: '¡Mentira! El Gran Sanedrín tenía 71 miembros.' },
  { verdad: false,
    historia: 'El Talmud dice que el maná siempre tenía gusto a papa.',
    explicacion: '¡Mentira! Según los sabios, tenía el gusto de lo que cada uno quisiera.' },
  { verdad: false,
    historia: 'Maimónides fue campeón de ajedrez de la corte del sultán Saladino.',
    explicacion: '¡Mentira! Fue médico de la corte, no campeón de ajedrez.' },
  { verdad: false,
    historia: 'En Buenos Aires, en el siglo XIX, la primera sinagoga funcionó adentro de un vagón de tranvía.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'La bandera de Israel iba a ser verde con una naranja en el medio, por las naranjas de Jaffa.',
    explicacion: '¡Mentira! Se inspiró en los colores del talit: blanco con franjas azules.' },
  { verdad: false,
    historia: 'La Mishná tiene un capítulo sobre las reglas de un juego de pelota muy parecido al fútbol.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'El reglamento del kibutz Deganía prohibía reírse los lunes para no distraerse del trabajo.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'En la Edad Media, el Jatán Torá tenía que pagar la leña de la sinagoga durante un año entero.',
    explicacion: '¡Mentira! Es inventado. Lo que sí es costumbre es que ofrezca un festejo o kidush.' },
  { verdad: false,
    historia: 'El Talmud cuenta que el primer "¡Mazal tov!" de la historia se lo dijo Adam a Javá.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'El shofar de Rosh Hashaná se puede hacer con un cuerno de vaca.',
    explicacion: '¡Mentira! El Talmud lo prohíbe, porque la vaca recuerda el becerro de oro.' },
  { verdad: false,
    historia: 'En Israel se planta un árbol por cada bebé que nace, por ley.',
    explicacion: '¡Mentira! No hay tal ley, aunque plantar árboles en Tu Bishvat sí es una costumbre.' },
  { verdad: false,
    historia: 'La Declaración de Independencia de Israel se firmó con una pluma de una paloma del Kotel.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'En Marruecos, las hakafot se hacían llevando el Sefer Torá dentro de una canoa, alrededor de una fuente.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'Einstein tenía una sucá en el jardín de su casa de Princeton y recibía invitados cada Sucot.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'La Torá manda comer sandía en Shavuot.',
    explicacion: '¡Mentira! En Shavuot es costumbre comer lácteos, pero no está en la Torá.' },
  { verdad: false,
    historia: 'Los Kohanim tenían que bendecir al pueblo parados en un solo pie.',
    explicacion: '¡Mentira! Bendicen parados, con los brazos levantados, pero en los dos pies.' },
  { verdad: false,
    historia: 'En el desierto, los hebreos festejaban los cumpleaños con tortas de maná.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'Según la tradición, Moshé y Aharón cumplían años el mismo día.',
    explicacion: '¡Mentira! La tradición dice que Moshé nació (y murió) el 7 de Adar, pero no dice eso de Aharón.' },
  { verdad: false,
    historia: 'El Talmud ordena regalarle un pez de colores a cada chico en Simjat Torá.',
    explicacion: '¡Mentira! La costumbre es darles caramelos y banderitas.' },
  { verdad: false,
    historia: 'La palabra "kipá" viene de "capitán", por los marineros judíos de Holanda.',
    explicacion: '¡Mentira! "Kipá" es una palabra hebrea que quiere decir cúpula.' },
  { verdad: false,
    historia: 'El Sefer Torá más largo del mundo mide tres kilómetros y se desenrolla una vez por año en Haifa.',
    explicacion: '¡Mentira! Un Sefer Torá suele medir entre 40 y 60 metros.' },
  { verdad: false,
    historia: 'Hilel y Shamai, los grandes sabios que siempre discutían, eran hermanos mellizos.',
    explicacion: '¡Mentira! No eran parientes: eran dos maestros con escuelas distintas.' },
  { verdad: false,
    historia: 'En la antigüedad, las hakafot se hacían corriendo, y el último en llegar pagaba el kidush.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'El rey David escribió todos los Salmos adentro de una sucá, durante 40 días.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'La Knéset tiene un Sefer Torá especial que solo se lee cuando hay empate en una votación.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'La Torá prohíbe cantar mientras se come.',
    explicacion: '¡Mentira! Al contrario: en Shabat es costumbre cantar zemirot en la mesa.' },
  { verdad: false,
    historia: 'En la época del Templo, los chicos que se portaban bien podían tocar el shofar del Kohen Gadol.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'Los primeros Sifrei Torá se escribían sobre hojas de palmera.',
    explicacion: '¡Mentira! Se escriben sobre pergamino, hecho de cuero.' },
  { verdad: false,
    historia: 'En el Templo había un "Kohen de la risa", encargado de contar chistes durante Sucot.',
    explicacion: '¡Mentira! Es inventado… aunque la alegría de Sucot en el Templo era enorme.' },
  { verdad: false,
    historia: 'Una ley israelí obliga a los colectivos a llevar banderitas de Simjat Torá durante la fiesta.',
    explicacion: '¡Mentira! Es inventado.' },
  { verdad: false,
    historia: 'Noaj metió en el arca dos ejemplares de cada animal, y además dos Sifrei Torá por las dudas.',
    explicacion: '¡Mentira! La Torá se entregó mucho después, en el Sinaí.' },
  { verdad: false,
    historia: 'En Simjat Torá está prohibido sentarse durante toda la noche.',
    explicacion: '¡Mentira! No existe esa prohibición (aunque con tanto baile, casi no hay tiempo).' },
  { verdad: false,
    historia: 'Theodor Herzl escribió "El Estado judío" en una sola noche, sin dormir.',
    explicacion: '¡Mentira! Lo escribió durante varias semanas de 1895.' },
  { verdad: false,
    historia: 'En la Edad Media, en algunas comunidades, el que se equivocaba leyendo la Torá tenía que cantar solo "Adón olam" parado sobre una silla.',
    explicacion: '¡Mentira! Es inventado. Si alguien se equivoca, simplemente lo corrigen.' },
  { verdad: false,
    historia: 'El Kotel se llama "Muro de los Lamentos" porque durante la noche se escucha llorar a las piedras.',
    explicacion: '¡Mentira! Se llama así porque la gente iba a lamentar la destrucción del Templo.' },
  { verdad: false,
    historia: 'Según el Talmud, las banderitas de Simjat Torá deben ser azules y blancas.',
    explicacion: '¡Mentira! El Talmud no habla de banderitas: la costumbre es de hace pocos siglos.' },
  { verdad: false,
    historia: 'El manto del Sefer Torá se lava una vez por año en el mar, en Hoshaná Rabá.',
    explicacion: '¡Mentira! Es inventado.' }
];
