/* =====================================================================
   BANCO DE VERDADERO O FALSO
   - "verdadero: true" si la afirmación es verdadera, "false" si es falsa.
   - "revisar: true" = conviene chequear el dato.
   ===================================================================== */

const DATOS_VERDADERO_FALSO = [
  { afirmacion: 'Simjat Torá significa "alegría de la Torá".', verdadero: true,
    explicacion: 'Simjá = alegría.' },
  { afirmacion: 'En Simjat Torá se empieza a leer de nuevo el libro Shemot.', verdadero: false,
    explicacion: 'Se vuelve a empezar desde Bereshit, el primer libro.' },
  { afirmacion: 'En Israel, Shminí Atzéret y Simjat Torá se festejan el mismo día.', verdadero: true, revisar: true,
    explicacion: 'En Israel es un solo día (22 de Tishrei); en la diáspora son dos días seguidos.' },
  { afirmacion: 'Las hakafot se hacen dando vueltas alrededor de la sucá.', verdadero: false,
    explicacion: 'Se dan vueltas alrededor de la bimá, adentro de la sinagoga.' },
  { afirmacion: 'Vezot Haberajá es la última parashá de la Torá.', verdadero: true,
    explicacion: 'Son los dos últimos capítulos de Devarim.' },
  { afirmacion: 'Moshé entró a la Tierra de Israel antes de morir.', verdadero: false,
    explicacion: 'La vio desde el monte Nevó, pero no entró.' },
  { afirmacion: 'Nadie sabe dónde está la tumba de Moshé.', verdadero: true,
    explicacion: '"Nadie conoce su sepultura hasta el día de hoy" (Devarim 34:6).' },
  { afirmacion: 'El Jatán Bereshit recibe la aliá en la que se lee el relato de la Creación.', verdadero: true,
    explicacion: 'Abre el nuevo ciclo de lectura.' },
  { afirmacion: 'Un Sefer Torá se puede imprimir en una imprenta.', verdadero: false,
    explicacion: 'Tiene que escribirlo a mano un sofer, sobre pergamino.' },
  { afirmacion: 'En Shminí Atzéret se sacude el lulav.', verdadero: false,
    explicacion: 'Las cuatro especies se usan solo durante los días de Sucot.' },
  { afirmacion: 'En Shminí Atzéret se empieza a pedir por la lluvia.', verdadero: true,
    explicacion: 'Con la Tefilat Guéshem y "mashiv harúaj umorid haguéshem".' },
  { afirmacion: 'La Torá tiene siete libros.', verdadero: false,
    explicacion: 'Tiene cinco: Bereshit, Shemot, Vaikrá, Bamidbar y Devarim.' },
  { afirmacion: 'El sol fue creado el primer día.', verdadero: false,
    explicacion: 'El primer día se creó la luz; el sol, la luna y las estrellas, el cuarto.' },
  { afirmacion: 'El ser humano fue creado el sexto día.', verdadero: true,
    explicacion: 'Junto con los animales de la tierra.' },
  { afirmacion: 'Antes de la paloma, Noaj mandó un cuervo fuera del arca.', verdadero: true,
    explicacion: 'Bereshit 8:7: primero el cuervo y después la paloma.' },
  { afirmacion: 'La primera palabra de la Torá es "Shemá".', verdadero: false,
    explicacion: 'Es "Bereshit": "Al principio".' },
  { afirmacion: 'La Torá está dividida en 54 parashiot.', verdadero: true,
    explicacion: 'Algunas semanas se leen dos juntas.' },
  { afirmacion: 'Vezot Haberajá se lee en un Shabat, como cualquier otra parashá.', verdadero: false,
    explicacion: 'Casi siempre se lee en Simjat Torá, no en Shabat.' },
  { afirmacion: 'En Kol Hanearim, los chicos suben a la Torá cubiertos con un talit.', verdadero: true,
    explicacion: 'Y se los bendice con "Hamalaj hagoel".' },
  { afirmacion: 'Las últimas palabras de la Torá son "leeiné kol Israel".', verdadero: true,
    explicacion: '"Ante los ojos de todo Israel" (Devarim 34:12).' },
  { afirmacion: 'El Jatán Torá lee la primera aliá de Bereshit.', verdadero: false,
    explicacion: 'El Jatán Torá cierra Devarim; el Jatán Bereshit abre Bereshit.' },
  { afirmacion: 'La haftará de Simjat Torá es del libro de Iehoshúa.', verdadero: true,
    explicacion: 'El primer capítulo: Iehoshúa toma el lugar de Moshé.' },
  { afirmacion: 'Iehoshúa era hermano de Moshé.', verdadero: false,
    explicacion: 'Era su ayudante y sucesor. Los hermanos de Moshé eran Aharón y Miriam.' },
  { afirmacion: 'Moshé murió a los 120 años.', verdadero: true,
    explicacion: 'Por eso se desea "hasta 120".' },
  { afirmacion: 'Sucot dura tres días.', verdadero: false,
    explicacion: 'Dura siete días, y el octavo es Shminí Atzéret.' },
  { afirmacion: 'Hoshaná Rabá es el séptimo día de Sucot.', verdadero: true,
    explicacion: 'Es el día anterior a Shminí Atzéret.' },
  { afirmacion: 'Simjat Torá se festeja en el mes de Nisán.', verdadero: false,
    explicacion: 'Se festeja en Tishrei. En Nisán cae Pésaj.' },
  { afirmacion: 'Si a un Sefer Torá le falta una letra, no se puede leer de él hasta corregirlo.', verdadero: true,
    explicacion: 'Tiene que estar completo y sin errores.' },
  { afirmacion: 'Se usa el iad (puntero) para no tocar el pergamino con los dedos.', verdadero: true,
    explicacion: 'Iad significa "mano".' },
  { afirmacion: 'Los Diez Mandamientos aparecen dos veces en la Torá.', verdadero: true,
    explicacion: 'En Shemot 20 y en Devarim 5.' },
  { afirmacion: 'El arca de Noaj se detuvo sobre el monte Sinaí.', verdadero: false,
    explicacion: 'Se detuvo sobre los montes de Ararat (Bereshit 8:4).' },
  { afirmacion: 'Iosef fue vendido por sus propios hermanos.', verdadero: true,
    explicacion: 'Terminó en Egipto, donde llegó a ser virrey.' },
  { afirmacion: 'En Vezot Haberajá, Moshé bendice solamente a la tribu de Leví.', verdadero: false,
    explicacion: 'Bendice a casi todas las tribus, una por una.' },
  { afirmacion: 'Miriam cantó con un pandero después de cruzar el mar.', verdadero: true,
    explicacion: 'Shemot 15:20.' },
  { afirmacion: 'Para leer la Torá en público alcanza con tres personas.', verdadero: false,
    explicacion: 'Hace falta un minián: diez personas.' },
  { afirmacion: 'En la antigua Tierra de Israel, la Torá se leía entera en unos tres años.', verdadero: true,
    explicacion: 'Era el ciclo trienal. Hoy se usa el ciclo anual.' },
  { afirmacion: 'Según muchos sabios, la última mitzvá de la Torá es escribir un Sefer Torá.', verdadero: true,
    explicacion: 'Se aprende de Devarim 31:19.' },
  { afirmacion: 'Shminí Atzéret es el primer día de Sucot.', verdadero: false,
    explicacion: 'Es el octavo día, justo después de los siete de Sucot.' },
  { afirmacion: 'En el Templo se ofrecían en total 70 toros durante los siete días de Sucot.', verdadero: true,
    explicacion: 'De 13 el primer día a 7 el séptimo: 70 en total.' },
  { afirmacion: 'La burra que habló era de Moshé.', verdadero: false,
    explicacion: 'Era de Bilaam (Bamidbar 22).' },
  { afirmacion: 'Los chicos llevan banderitas en las hakafot de Simjat Torá.', verdadero: true,
    explicacion: 'Es una costumbre de hace varios siglos.' },
  { afirmacion: 'La Torá termina contando la muerte de Aharón.', verdadero: false,
    explicacion: 'Termina con la muerte de Moshé. Aharón muere antes, en Bamidbar.' }
];
